AWSTemplateFormatVersion: 2010-09-09

# This CloudFormation template deploys a basic EC2:
# - with httpd & very simple website but not acessible from outside
# - the key-pair for ssh into the instance
# - security group to allow ingress port 22 for ssh into the instance
# - egress to internet

Parameters:
  KeyName:
    Description: Key Pair for EC2
    Type: 'AWS::EC2::KeyPair::KeyName'
    
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-west-2a
      ImageId: ami-0c2ab3b8efb09f272
      InstanceType: t2.nano
      Tags:
        - Key: Name
          Value: EC2 with ingress port 22
      SecurityGroups:
        - !Ref EC2sshSecurityGroup
      KeyName: !Ref KeyName
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Hello from Region us-west-2a</h1>" > /var/www/html/index.html

  EC2sshSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "EC2ssh Security Group"
      GroupDescription: EC2 with ssh ingress port 22
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          CidrIp: "0.0.0.0/0"
          FromPort: 22
          ToPort: 22
        - IpProtocol: "tcp"
          CidrIp: "0.0.0.0/0"
          FromPort: 80
          ToPort: 80