AWSTemplateFormatVersion: 2010-09-09

# This CloudFormation template deploys a basic EC2:
# - with httpd
# - very simple website
# - security group to allow ingress port 80, and egress to internet

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-west-2a
      ImageId: ami-0c2ab3b8efb09f272
      InstanceType: t2.nano
      Tags:
        - Key: Name
          Value: EC2 with simple website on httpd server
      SecurityGroups:
        - !Ref EC2httpdSecurityGroup
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Hello from Region us-west-2a</h1>" > /var/www/html/index.html

  EC2httpdSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "EC2httpd Security Group"
      GroupDescription: EC2 with httpd ingress port 80
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          CidrIp: "0.0.0.0/0"
          FromPort: 80
          ToPort: 80    